### ISSUE TITLE
Remove unused file

### ISSUE THREAD

**Issue by varokas** [ETDA/e-TaxInvoice-PDFgen#1]
These files are not necessary in the project. Please delete them and put in .gitignore. People can download the binaries via Release page.

.vs/
eTaxInvoicePdfGenerator/bin/
eTaxInvoicePdfGenerator/obj/
publish/

**Comment by aixasz** [comment]
https://github.com/ETDA/e-TaxInvoice-PDFgen/pull/3

We have a pull request for this.

**Comment by pragasitcha** [comment]
@varokas @aixasz  

 Thankyou for your feedback and valued information .  Your issued are being reviewd by our engineer.
