### ISSUE TITLE
Use NuGet to reference iTextSharp

### ISSUE THREAD

**Issue by varokas** [ETDA/e-TaxInvoice-PDFgen#2]
So that we can remove another binary in
e-TaxInvoice-PDFgen/eTaxInvoicePdfGenerator/libsITEXT/

https://www.nuget.org/packages/iTextSharp/

**Comment by pragasitcha** [comment]
@varokas  Thankyou for your feedback and valued information  i will raise this issue to our next meeting.

**Comment by pragasitcha** [comment]
@varokas 

Hello varokas thank for your patience . due to last meeting the issue raised up during our session.
We will use  Nuget  to reference iTextSharp and this will release on our next version
