### ISSUE TITLE
Remove code commenting.

### ISSUE THREAD

**Issue by aixasz** [ETDA/e-TaxInvoice-PDFgen#6]
To reduce code smells.  

I've created PR for [this](https://github.com/ETDA/e-TaxInvoice-PDFgen/pull/5 ).

**Comment by pragasitcha** [comment]
เรียนคุณ @aixasz 

ขอบคุณสำหรับ feedback ครับ ทางทีมจะทำการลบ unsoed comment ออกจาภายในเวอร์ชันถัดไปครับ
